In [1]:
#15. Create a 2d array with 1 on the border and 0 inside

import numpy as np


rows, columns = 5, 5  


array = np.zeros((rows, columns), dtype=int)


array[0, :] = 1  
array[-1, :] = 1 
array[:, 0] = 1  
array[:, -1] = 1  

print(array)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
