In [1]:
#16. How to add a border (filled with 0's) around an existing array?

import numpy as np


existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])


rows, columns = existing_array.shape
border_value = 0


new_array = np.zeros((rows + 2, columns + 2), dtype=existing_array.dtype)


new_array[1:-1, 1:-1] = existing_array

print("Existing Array:")
print(existing_array)
print("\nArray with Border:")
print(new_array)


Existing Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with Border:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]
