In [1]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


import numpy as np

matrix = np.zeros((5, 5))

for i in range(1, 5):
    matrix[i, i-1] = i

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
