In [1]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern

import numpy as np


matrix = np.zeros((8, 8), dtype=int)


matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
