In [1]:
#21. Create a checkerboard 8x8 matrix using the tile function

import numpy as np
checkerboard = np.array([[0, 1], [1, 0]])


matrix = np.tile(checkerboard, (4, 4))

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
