In [1]:
#22. Normalize a 5x5 random matrix

import numpy as np


random_matrix = np.random.rand(5, 5)

mean_value = np.mean(random_matrix)
std_deviation = np.std(random_matrix)

normalized_matrix = (random_matrix - mean_value) / std_deviation

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.01707424 0.69004326 0.80905251 0.92193778 0.74999894]
 [0.56765154 0.52404692 0.51434323 0.73275354 0.44809441]
 [0.44365732 0.3350243  0.90364135 0.46053699 0.29794512]
 [0.32499866 0.6031735  0.69083195 0.7062089  0.41774976]
 [0.41559786 0.72792615 0.08364517 0.73651693 0.1708666 ]]

Normalized Matrix:
[[-2.17342954  0.66855389  1.1711362   1.64785661  0.92174989]
 [ 0.15168723 -0.03245737 -0.07343654  0.84892163 -0.35320879]
 [-0.37194683 -0.8307098   1.57058982 -0.30066311 -0.98729712]
 [-0.87304861  0.30169835  0.67188457  0.73682223 -0.48135582]
 [-0.49044344  0.82853531 -1.89229705  0.86481466 -1.52395637]]
