In [4]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4


import numpy as np

matrix = np.arange(5).reshape(5, 1) + np.arange(5)

print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
