In [4]:
# 52. Consider a random vector with shape (100,2) representing coordinates,
#find point by point distances

import numpy as np
from scipy.spatial import distance


random_coordinates = np.random.rand(100, 2)

distances = distance.cdist(random_coordinates, random_coordinates)

print(distances)


[[0.         0.47361809 0.983349   ... 0.3654718  1.10915251 0.53374558]
 [0.47361809 0.         0.66979641 ... 0.27971156 0.71585743 0.61565176]
 [0.983349   0.66979641 0.         ... 0.61796691 0.23416826 0.65126874]
 ...
 [0.3654718  0.27971156 0.61796691 ... 0.         0.75166546 0.33924773]
 [1.10915251 0.71585743 0.23416826 ... 0.75166546 0.         0.85749347]
 [0.53374558 0.61565176 0.65126874 ... 0.33924773 0.85749347 0.        ]]
