In [9]:
# 57. How to randomly place p elements in a 2D array? 

import numpy as np

rows, cols = 5, 5  
array = np.zeros((rows, cols), dtype=int) 

p = 5  

random_coords = np.random.randint(0, rows, size=(p, 2))

for coord in random_coords:
    row, col = coord
    array[row, col] = 1  

print(array)

[[0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 1 0 0 1]
 [0 0 0 0 1]]
