In [5]:
## 59. How to sort an array by the nth column?

import numpy as np

array = np.array([[3, 6, 2],
                  [1, 8, 4],
                  [5, 7, 9]])

n = 1

sorted_indices = np.argsort(array[:, n])

sorted_array = array[sorted_indices]

print("Original Array:")
print(array)

print("\nSorted Array by Column", n)
print(sorted_array)


Original Array:
[[3 6 2]
 [1 8 4]
 [5 7 9]]

Sorted Array by Column 1
[[3 6 2]
 [5 7 9]
 [1 8 4]]
