In [3]:
# 69. How to get the diagonal of a dot product? 

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

dot_product = np.dot(A, B)


diagonal = np.diag(dot_product)

print("Dot Product:")
print(dot_product)

print("\nDiagonal of Dot Product:")
print(diagonal)

Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of Dot Product:
[30 69 90]
