In [4]:
# 72. How to swap two rows of an array?

import numpy as np


array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


row1_index = 0  
row2_index = 2  

# Swap the rows
temp_row = array[row1_index].copy()  
array[row1_index] = array[row2_index]  
array[row2_index] = temp_row  


print("Array with Swapped Rows:")
print(array)


Array with Swapped Rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]
