In [9]:
# 76. Consider a one-dimensional array Z,
#build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and 
#each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

import numpy as np

Z = np.array([1, 2, 3, 4, 5])

num_rows = len(Z) - 2  
row_size = 3  

result = np.empty((num_rows, row_size), dtype=Z.dtype)

for i in range(num_rows):
    result[i] = Z[i:i + row_size]

print("Resulting Array:")
print(result)


Resulting Array:
[[1 2 3]
 [2 3 4]
 [3 4 5]]
