In [15]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, 
#how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

import numpy as np

def point_to_line_distance(point, line_start, line_end):
    AB = line_end - line_start
    AP = point - line_start


    cross_product = np.cross(AP, AB)
    magnitude_AB = np.linalg.norm(AB)


    distance = np.abs(cross_product) / magnitude_AB

    return distance

def compute_distances_to_lines(P, P0, P1):
    num_points = len(P)
    num_lines = len(P0)
    
    distances = np.zeros((num_points, num_lines))  # Initialize an array to store distances
    
    for i in range(num_points):
        for j in range(num_lines):
            distances[i, j] = point_to_line_distance(P[i], P0[j], P1[j])
    
    return distances

P0 = np.array([[1, 1], [2, 2], [3, 3]])
P1 = np.array([[4, 4], [5, 5], [6, 6]])
P = np.array([[2, 4], [3, 5], [5, 3]])


distances = compute_distances_to_lines(P, P0, P1)
print("Distances to lines:")
print(distances)


Distances to lines:
[[1.41421356 1.41421356 1.41421356]
 [1.41421356 1.41421356 1.41421356]
 [1.41421356 1.41421356 1.41421356]]
