In [36]:
# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element 
#(pad with a `fill` value when necessary)

import numpy as np

def extract_centered_subpart(array, center, shape, fill_value=0):
   
    rows, cols = array.shape
    row_center, col_center = center
    row_half, col_half = shape[0] // 2, shape[1] // 2
    
    # Calculate the starting and ending row and column indices for the subpart
    start_row = max(0, row_center - row_half)
    end_row = min(rows, row_center + row_half + 1)
    start_col = max(0, col_center - col_half)
    end_col = min(cols, col_center + col_half + 1)
    
    # Create an empty subpart with the specified shape and fill it with fill_value
    subpart = np.full(shape, fill_value, dtype=array.dtype)
    
    # Calculate the indices for copying data from the input array to the subpart
    subpart_start_row = max(0, row_half - (row_center - start_row))
    subpart_end_row = min(shape[0], shape[0] - (row_center + row_half - end_row))
    subpart_start_col = max(0, col_half - (col_center - start_col))
    subpart_end_col = min(shape[1], shape[1] - (col_center + col_half - end_col))
    
    # Copy data from the input array to the subpart
    subpart[subpart_start_row:subpart_end_row, subpart_start_col:subpart_end_col] = \
        array[start_row:end_row, start_col:end_col]
    
    return subpart

# Example usage:
input_array = np.array([[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10],
                        [11, 12, 13, 14, 15]])

center_element = (1, 2)
subpart_shape = (3, 3)
fill_value = 0

subpart = extract_centered_subpart(input_array, center_element, subpart_shape, fill_value)
print("Extracted Subpart:")
print(subpart)


Extracted Subpart:
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
