In [9]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

import numpy as np

matrix = np.random.rand(10, 10)

block_size = 3

blocks = []

for i in range(10 - block_size + 1):
    for j in range(10 - block_size + 1):
        block = matrix[i:i+block_size, j:j+block_size]
        blocks.append(block)

blocks_array = np.array(blocks)

for idx, block in enumerate(blocks_array):
    print(f"Block {idx + 1}:\n{block}\n")

Block 1:
[[0.05706789 0.76554069 0.41019113]
 [0.43042542 0.45744026 0.49030919]
 [0.19535145 0.78805061 0.99398043]]

Block 2:
[[0.76554069 0.41019113 0.47669222]
 [0.45744026 0.49030919 0.18273432]
 [0.78805061 0.99398043 0.14772309]]

Block 3:
[[0.41019113 0.47669222 0.06494065]
 [0.49030919 0.18273432 0.75685486]
 [0.99398043 0.14772309 0.33902916]]

Block 4:
[[0.47669222 0.06494065 0.1710222 ]
 [0.18273432 0.75685486 0.65334619]
 [0.14772309 0.33902916 0.24632228]]

Block 5:
[[0.06494065 0.1710222  0.74699334]
 [0.75685486 0.65334619 0.94582775]
 [0.33902916 0.24632228 0.46929871]]

Block 6:
[[0.1710222  0.74699334 0.84866126]
 [0.65334619 0.94582775 0.02696171]
 [0.24632228 0.46929871 0.4151959 ]]

Block 7:
[[0.74699334 0.84866126 0.73067893]
 [0.94582775 0.02696171 0.49011577]
 [0.46929871 0.4151959  0.96680784]]

Block 8:
[[0.84866126 0.73067893 0.80585982]
 [0.02696171 0.49011577 0.93818648]
 [0.4151959  0.96680784 0.7378642 ]]

Block 9:
[[0.43042542 0.45744026 0.49030919]
 [0