In [9]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

import numpy as np

class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __getitem__(self, index):
        i, j = index
        if i <= j:
            return super(SymmetricArray, self).__getitem__((i, j))
        else:
            return super(SymmetricArray, self).__getitem__((j, i))

    def __setitem__(self, index, value):
        i, j = index
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)


data = np.array([[1, 2, 3],
                 [2, 4, 5],
                 [3, 5, 6]])

symmetric_array = SymmetricArray(data)


print("symmetric_array[0, 1] =", symmetric_array[0, 1])  # Should print 2
print("symmetric_array[1, 0] =", symmetric_array[1, 0])  # Should also print 2

symmetric_array[0, 2] = 7
print("After setting symmetric_array[0, 2] to 7:")
print(symmetric_array)


symmetric_array[0, 1] = 2
symmetric_array[1, 0] = 2
After setting symmetric_array[0, 2] to 7:
[[1 2 7]
 [2 4 5]
 [7 5 6]]
