In [9]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

import numpy as np

array = np.random.randint(1, 10, size=(16, 16))

block_size = 4

num_blocks_x = array.shape[0] // block_size
num_blocks_y = array.shape[1] // block_size

block_sums = np.empty((num_blocks_x, num_blocks_y), dtype=int)

for i in range(num_blocks_x):
    for j in range(num_blocks_y):
        block = array[i * block_size:(i + 1) * block_size, j * block_size:(j + 1) * block_size]
        block_sums[i, j] = np.sum(block)

print("Block Sums:")
print(block_sums)


Block Sums:
[[ 92  61  82  80]
 [ 80  68 104 110]
 [ 75  92  81  58]
 [ 75  86  79  71]]
