In [1]:
#9. Create a 3x3 matrix with values ranging from 0 to 8

import numpy as np

# Create a NumPy array with values ranging from 0 to 8
my_array = np.arange(9)

# Reshape the array into a 3x3 matrix
my_matrix = my_array.reshape(3, 3)

print(my_matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
