In [4]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

import numpy as np


matrix = np.array([[1, 1, 1],
                   [2, 2, 3],
                   [4, 4, 4],
                   [5, 6, 7],
                   [8, 8, 9],
                   [10, 11, 11],
                   [12, 13, 14],
                   [15, 15, 15],
                   [16, 17, 18],
                   [19, 20, 21]])


unequal_rows = matrix[~np.all(matrix[:, 1:] == matrix[:, :-1], axis=1)]


print("Rows with unequal values:")
print(unequal_rows)


Rows with unequal values:
[[ 2  2  3]
 [ 5  6  7]
 [ 8  8  9]
 [10 11 11]
 [12 13 14]
 [16 17 18]
 [19 20 21]]
