In [7]:
# 95. Convert a vector of ints into a matrix binary representation

import numpy as np

vector = np.array([5, 2, 7, 0, 3])

max_value = np.max(vector)

num_bits = int(np.log2(max_value)) + 1

binary_matrix = ((vector[:, None] & (1 << np.arange(num_bits))) > 0).astype(int)

print("Binary Matrix Representation:")
print(binary_matrix)

Binary Matrix Representation:
[[1 0 1]
 [0 1 0]
 [1 1 1]
 [0 0 0]
 [1 1 0]]
