In [7]:
# 96. Given a two dimensional array, how to extract unique rows?

import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6]])

unique_rows = np.unique(array, axis=0)

print("Unique Rows:")
print(unique_rows)

Unique Rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
