In [11]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, 
#outer, sum, and mul function

import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Equivalent einsum for inner (dot) product
inner_product = np.einsum('i,i->', A, B)
print("Inner (Dot) Product:", inner_product)

# Equivalent einsum for outer product
outer_product = np.einsum('i,j->ij', A, B)
print("Outer Product:")
print(outer_product)

# Equivalent einsum for summation (sum)
summation = np.einsum('i->', A)
print("Summation:", summation)

# Equivalent einsum for element-wise multiplication
elementwise_multiplication = np.einsum('i,i->i', A, B)
print("Element-wise Multiplication:")
print(elementwise_multiplication)



Inner (Dot) Product: 32
Outer Product:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Summation: 6
Element-wise Multiplication:
[ 4 10 18]
