In [15]:
#12. Create a 3x3x3 array with random values

import numpy as np


my_matrix = np.random.rand(3,3)

print(my_matrix)


[[0.54176396 0.34898801 0.47591968]
 [0.19722606 0.07815905 0.75510303]
 [0.0026937  0.6163657  0.76786457]]
